### ISSUE TITLE
Player health should decrease when near walls and touching enemies

### ISSUE THREAD

**Issue by jeffsieu** [jeffsieu/last-man-sitting#1]
- [x] Player health bar
- [ ] Player health decreases near boundaries
- [x] Enemies damage player
- [ ] Fix bug causing player not to be damaged by same enemy

**Comment by owenl131** [comment]
Why health decrease near boundaries?

**Comment by jeffsieu** [comment]
To force them not to use the wall as a way to back up against the recoil

**Comment by daniellimws** [comment]
> Fix bug causing player not to be damaged by same enemy

This is fixed?

> Player health decreases near boundaries

Still want?

**Comment by jeffsieu** [comment]
No it's not fixed. To fix, we need to detect for collision again when the damage cooldown is over.

As for the boundary thing, maybe we can have both walled and unwalled maps? Then for the maps without walls, the player will fall

**Comment by daniellimws** [comment]
I think yea can have both. Then some types of walls will deal damage, ok?

**Comment by jeffsieu** [comment]
Ok, but I think this also can consider later during level design stage

**Comment by daniellimws** [comment]
Checked: problem is not with damage cooldown. It is because the collision is not detected when the enemy just "sticks" on the player. I think the collision is only detected when at least one entity is moving.

**Reproducible by letting the enemy touch the corners of player.**

* `KinematicCollision get_slide_collision ( int slide_idx )`
Returns a KinematicCollision, which contains information about a collision that occurred during the last move_and_slide call. Since the body can collide several times in a single call to move_and_slide, you must specify the index of the collision in the range 0 to (get_slide_count - 1).

* `int get_slide_count ( ) const`
Returns the number of times the body collided and changed direction during the last call to move_and_slide.

Sienz..

**Comment by jeffsieu** [comment]
ya la, so after the cool down cannot check the collision meh?

**Comment by daniellimws** [comment]
The cooldown already works all this time. But the engine doesn't even detect the collision between player and enemy under certain scenarios.

**Comment by jeffsieu** [comment]
I thought it's because the bodies are still touching, so even if they keep touching it won't detect as a collision?

**Comment by daniellimws** [comment]
But sometimes it does detect even when they are touching. I think what matters is whether they are sliding.
